### ISSUE TITLE
Roadmap to Beta

### ISSUE THREAD

**Issue by HallM** [HallM/Lisplate#1]
# Road to beta

- [x] Initial syntax spec in peg format
- [x] Initial compiler
- [x] Base runtime
- [x] Including other templates

- [x] Improved syntax errors for compiler

- [x] Components
  - [x] Creating an key:value map to pass as parameter to a component
- [x] View Models along with parameters
- [x] Strings/messages file

- [x] Async templates
- ~~[] Streaming output~~ Post beta release

- [x] Work in browsers
- [x] Explore working in other JS engines (ex Rhino, Nashorn, Ringo)

- [ ] Specs and unit tests

- [ ] Better documentation site
- [ ] Contributing and other community docs

**Comment by HallM** [comment]
Docs: No documentation on helpers exists at all right now.
